CREATE TABLE tb_contato (id INTEGER PRIMARY KEY, nome TEXT NOT NULL, endereco TEXT NOT NULL, site TEXT NOT NULL, telefone TEXT NOT NULL, relevancia REAL);
CREATE TABLE tb_teste (id INTEGER PRIMARY KEY, nome TEXT NOT NULL);
CREATE TABLE tb_urso (id INTEGER PRIMARY KEY, nome TEXT NOT NULL);